In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
# get data
df_preprocessed = pd.read_csv("Absenteeism_preprocessed.csv")
df_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   
5         0         0         0         1             7                4   
6         0         0         0         1             7                4   
7         0         0         0         1             7                4   
8         0         0         1         0             7                0   
9         0         0         0         1             7                0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2  
5               31          0         0     0                          2  
6               27          0         1     4                          8  
7               23          0         4     0                          4  
8               25          0         2     0                         40  
9               29          1         1     1                          8

In [15]:
# Decide threshhold for target
df_preprocessed["Absenteeism Time in Hours"].median()

3.0

In [16]:
# get encoded target values in 1-D array based on time below and above median
targets = np.where(df_preprocessed["Absenteeism Time in Hours"] > 
                   df_preprocessed["Absenteeism Time in Hours"].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [17]:
# add target to df
df_preprocessed["Excessive Absenteeism"] = targets
df_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [18]:
# check spread of targets - % of 1 values
targets.sum() / targets.shape[0]

0.45571428571428574

## Checkpoint with Encoded Targets

In [19]:
df_targets = df_preprocessed.drop(columns=["Absenteeism Time in Hours"])
df_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

In [20]:
# check to see if dfs are different
df_targets is df_preprocessed

False

In [21]:
# get features
unscaled_inputs = df_targets.iloc[:,:-1]
unscaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Day of the Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  
0               30          0         2     1  
1               31          0         1     0  
2               31          0         0     0  
3               24          0         2     0  
4               30          0         2     1

In [23]:
# standardizing features
from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# fit_transform data
# scaled_inputs = sc.fit_transform(unscaled_inputs)

In [51]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [52]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('scaler', StandardScaler(), ['Month Values',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets'])], remainder='passthrough')

In [53]:
scaled_inputs = np.array(ct.fit_transform(unscaled_inputs))
scaled_inputs


array([[ 0.18272635, -0.68370352,  1.00584437, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.18272635, -0.68370352, -1.57468098, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.18272635, -0.00772546, -0.6541427 , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.3882935 ,  0.66825259,  1.62456682, ...,  0.        ,
         0.        ,  1.        ],
       [-0.3882935 ,  0.66825259,  0.19094163, ...,  0.        ,
         1.        ,  1.        ],
       [-0.3882935 ,  0.66825259,  1.03602595, ...,  0.        ,
         1.        ,  0.        ]])

In [54]:
scaled_inputs[0]

array([ 0.18272635, -0.68370352,  1.00584437,  0.41281584, -0.53606239,
       -0.80633129,  0.76743118,  0.88046927,  0.26848661,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ])

In [24]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [55]:
# split training and testing data
from sklearn.model_selection import train_test_split

In [56]:
X_train, X_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [57]:
# check training and testing shapes
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(560, 14) (560,) (140, 14) (140,)


# Logistic Regression

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [59]:
# fit training data
regressor = LogisticRegression()
regressor.fit(X_train, y_train)

LogisticRegression()

In [60]:
# get accuracy of model using training data
regressor.score(X_train, y_train)

0.775

In [61]:
# get accuracy of model using testing data
# predictions
predictions = regressor.predict(X_test)

In [62]:
metrics.accuracy_score(y_test, predictions)

0.7428571428571429

## Summary Table

In [64]:
# creating summary df with coefficients for each column
# get feature names for columns
features = ['Month Values',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index',
       'Children', 'Pets', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [65]:
# create df
summary = pd.DataFrame(columns=['Features'], data=features)
summary["Coefficient"] = np.transpose(regressor.coef_)
summary

Features  Coefficient
0              Month Values     0.166248
1           Day of the Week    -0.084370
2    Transportation Expense     0.612733
3          Distance to Work    -0.007797
4                       Age    -0.165923
5   Daily Work Load Average    -0.000147
6           Body Mass Index     0.271811
7                  Children     0.361990
8                      Pets    -0.285511
9                  Reason_1     2.800965
10                 Reason_2     0.934858
11                 Reason_3     3.095616
12                 Reason_4     0.856587
13                Education    -0.205738

In [66]:
summary.index = summary.index + 1
summary

Features  Coefficient
1              Month Values     0.166248
2           Day of the Week    -0.084370
3    Transportation Expense     0.612733
4          Distance to Work    -0.007797
5                       Age    -0.165923
6   Daily Work Load Average    -0.000147
7           Body Mass Index     0.271811
8                  Children     0.361990
9                      Pets    -0.285511
10                 Reason_1     2.800965
11                 Reason_2     0.934858
12                 Reason_3     3.095616
13                 Reason_4     0.856587
14                Education    -0.205738

In [67]:
# create value at index 0
summary.loc[0] = ['Intercept', regressor.intercept_[0]]
summary.sort_index(inplace = True)
summary

Features  Coefficient
0                 Intercept    -1.656109
1              Month Values     0.166248
2           Day of the Week    -0.084370
3    Transportation Expense     0.612733
4          Distance to Work    -0.007797
5                       Age    -0.165923
6   Daily Work Load Average    -0.000147
7           Body Mass Index     0.271811
8                  Children     0.361990
9                      Pets    -0.285511
10                 Reason_1     2.800965
11                 Reason_2     0.934858
12                 Reason_3     3.095616
13                 Reason_4     0.856587
14                Education    -0.205738

In [68]:
# get exponentials of coefficients
summary["Odds Ratio"] = np.exp(summary.Coefficient)

In [69]:
summary

Features  Coefficient  Odds Ratio
0                 Intercept    -1.656109    0.190880
1              Month Values     0.166248    1.180866
2           Day of the Week    -0.084370    0.919091
3    Transportation Expense     0.612733    1.845467
4          Distance to Work    -0.007797    0.992233
5                       Age    -0.165923    0.847112
6   Daily Work Load Average    -0.000147    0.999853
7           Body Mass Index     0.271811    1.312340
8                  Children     0.361990    1.436184
9                      Pets    -0.285511    0.751630
10                 Reason_1     2.800965   16.460523
11                 Reason_2     0.934858    2.546851
12                 Reason_3     3.095616   22.100858
13                 Reason_4     0.856587    2.355110
14                Education    -0.205738    0.814046

In [70]:
# sort by greatest odds
summary.sort_values('Odds Ratio', ascending = False)

Features  Coefficient  Odds Ratio
12                 Reason_3     3.095616   22.100858
10                 Reason_1     2.800965   16.460523
11                 Reason_2     0.934858    2.546851
13                 Reason_4     0.856587    2.355110
3    Transportation Expense     0.612733    1.845467
8                  Children     0.361990    1.436184
7           Body Mass Index     0.271811    1.312340
1              Month Values     0.166248    1.180866
6   Daily Work Load Average    -0.000147    0.999853
4          Distance to Work    -0.007797    0.992233
2           Day of the Week    -0.084370    0.919091
5                       Age    -0.165923    0.847112
14                Education    -0.205738    0.814046
9                      Pets    -0.285511    0.751630
0                 Intercept    -1.656109    0.190880

## Testing Data Accuracy

In [71]:
regressor.score(X_test, y_test)

0.7428571428571429

In [72]:
# predicting the probability of target from features
predicted_proba = regressor.predict_proba(X_test)
predicted_proba

array([[0.73838887, 0.26161113],
       [0.60860095, 0.39139905],
       [0.40910176, 0.59089824],
       [0.80489361, 0.19510639],
       [0.0732329 , 0.9267671 ],
       [0.31965834, 0.68034166],
       [0.31302205, 0.68697795],
       [0.13341719, 0.86658281],
       [0.79712508, 0.20287492],
       [0.75274419, 0.24725581],
       [0.48222467, 0.51777533],
       [0.1964133 , 0.8035867 ],
       [0.07857533, 0.92142467],
       [0.70622367, 0.29377633],
       [0.30708515, 0.69291485],
       [0.57055326, 0.42944674],
       [0.54143955, 0.45856045],
       [0.57205946, 0.42794054],
       [0.38194051, 0.61805949],
       [0.04857923, 0.95142077],
       [0.6977753 , 0.3022247 ],
       [0.79578125, 0.20421875],
       [0.3949288 , 0.6050712 ],
       [0.42248618, 0.57751382],
       [0.26634773, 0.73365227],
       [0.75608758, 0.24391242],
       [0.51088279, 0.48911721],
       [0.86807166, 0.13192834],
       [0.20221381, 0.79778619],
       [0.78635626, 0.21364374],
       [0.

## Save Model

In [73]:
import pickle

In [74]:
# Logistic Regressor Model
with open('model', 'wb') as file:
    pickle.dump(regressor, file)

In [75]:
# Scaler - Column transformer Model
with open('scaler', 'wb') as file:
    pickle.dump(ct, file)